export type SourceOrigin = "paste" | "import" | "reference";
export type MediaType = "text/plain" | "text/html" | "application/json" | "application/pdf" | "image/png" | "image/jpeg" | "image/webp";
export type SourceSensitivity = "public" | "internal" | "restricted";
export type SourceDuplicatePolicy = "allow" | "warn" | "block";
export type SourceIntakeStatus = "pending" | "approved" | "rejected";
export type SourceWatchStatus = "never" | "changed" | "unchanged" | "failed";
export type RetentionState = "unscheduled" | "scheduled" | "due" | "blocked" | "held" | "purged";
export type RetentionQueueState = "" | RetentionState;

export type CaptureSummary = {
  capture_id: string;
  source_id: string;
  version: number;
  media_type: MediaType;
  sha256: string;
  bytes: number;
  captured_by: string;
  captured_at: string;
};
export type Capture = CaptureSummary & { content?: string; content_base64?: string };
export type TextCapture = CaptureSummary & { content: string };
export type ExtractionStatus = "succeeded" | "unsupported" | "failed";
export type SourceExtraction = {
  extraction_id: string;
  workspace_id: string;
  source_id: string;
  capture_id: string;
  method: string;
  status: ExtractionStatus;
  output_sha256?: string;
  output_bytes: number;
  message?: string;
  created_by: string;
  created_at: string;
  text?: string;
};
export type SourceExtractionPage = { items: SourceExtraction[]; next_cursor: string | null };
export type SourceSummary = {
  source_id: string;
  workspace_id: string;
  title: string;
  origin: SourceOrigin;
  url?: string;
  filename?: string;
  published_at?: string;
  duplicate_policy?: SourceDuplicatePolicy;
  created_by: string;
  created_at: string;
  retention_until?: string;
  retention_updated_by?: string;
  retention_updated_at?: string;
  sensitivity: SourceSensitivity;
  privacy_updated_by?: string;
  privacy_updated_at?: string;
  legal_hold: boolean;
  legal_hold_reason?: string;
  purged_at?: string;
  purged_by?: string;
  purge_reason?: string;
  latest_capture: CaptureSummary | null;
};
export type SourceDetail = { source: SourceSummary; captures: CaptureSummary[] };
export type SourceIntakeCandidate = {
  intake_id: string;
  workspace_id: string;
  title: string;
  origin: "reference" | "import";
  url?: string;
  filename?: string;
  media_type?: MediaType;
  note?: string;
  created_by: string;
  created_at: string;
  status: SourceIntakeStatus;
  reviewed_by?: string;
  reviewed_at?: string;
  review_note?: string;
  source_id?: string;
};
export type SourceIntakePage = Page<SourceIntakeCandidate>;
export type CreateSourceIntake = {
  title: string;
  origin?: "reference" | "import";
  url?: string;
  filename?: string;
  media_type?: MediaType;
  content?: string;
  content_base64?: string;
  note?: string;
};
export type ReviewSourceIntake = { decision: "approved" | "rejected"; note: string };
export type SourceIntakeReviewResult = { candidate: SourceIntakeCandidate; source?: SourceSummary };
export type SourceWatch = {
  workspace_id: string;
  source_id: string;
  enabled: boolean;
  interval_seconds: number;
  next_run_at?: string;
  last_run_at?: string;
  last_status: SourceWatchStatus;
  last_capture_id?: string;
  last_error?: string;
  lease_owner?: string;
  lease_until?: string;
  updated_by?: string;
  updated_at?: string;
};
export type ConfigureSourceWatch = { enabled: boolean; interval_seconds: number };
export type SourceWatchRunResult = { watch: SourceWatch; changed: boolean; capture?: CaptureSummary };
export type SourceAlertKind = "capture_changed" | "watch_failed" | "question_gap" | "record_gap" | "cluster_gap";
export type SourceAlertDelivery = {
  workspace_id: string;
  account_id: string;
  email_enabled: boolean;
  kinds: SourceAlertKind[];
  updated_at: string;
};
export type SourceAlertDeliveryInput = { email_enabled: boolean; kinds: SourceAlertKind[] };
export type SourceAlert = {
  alert_id: string;
  workspace_id: string;
  source_id?: string;
  capture_id?: string;
  question_id?: string;
  record_id?: string;
  cluster_id?: string;
  kind: SourceAlertKind;
  title: string;
  detail: string;
  dedupe_key?: string;
  source_title?: string;
  created_by: string;
  created_at: string;
  seen_at?: string;
  active?: boolean;
};
export type SourceGapAlertsRefresh = { active_gap_count: number };
export type SourceAlertPage = { items: SourceAlert[]; next_cursor: string | null };
export type Page<T> = { items: T[]; next_cursor: string | null };
export type SourceSearchResult = {
  source_id: string;
  source_title: string;
  capture_id: string;
  capture_version: number;
  media_type: MediaType;
  extraction_id?: string;
  extraction_method?: string;
  excerpt: string;
  match: string;
  match_start: number;
  match_end: number;
};
export type SourceSearchPage = Page<SourceSearchResult>;
export type AddSource = {
  title: string;
  origin: SourceOrigin;
  url?: string;
  filename?: string;
  published_at?: string;
  media_type?: MediaType;
  content?: string;
  content_base64?: string;
};
export type SetSourceRetention = { retention_until: string | null };
export type SetSourcePublication = { published_at: string | null };
export type SetSourceDuplicatePolicy = { duplicate_policy: SourceDuplicatePolicy };
export type SetSourcePrivacy = { sensitivity: SourceSensitivity; legal_hold: boolean; legal_hold_reason: string };
export type PurgeDependencies = {
  capture_count: number;
  observation_count: number;
  extraction_count: number;
  assistance_operation_count: number;
  assistance_proposal_count: number;
};
export type SourceRetentionReview = {
  source_id: string;
  state: RetentionState;
  retention_until?: string;
  sensitivity: SourceSensitivity;
  legal_hold: boolean;
  legal_hold_reason?: string;
  dependencies: PurgeDependencies;
  eligible: boolean;
  blockers: string[];
};
export type PurgeSource = { purged: boolean; review: SourceRetentionReview };
export type RetentionQueueItem = { source: Omit<SourceSummary, "latest_capture">; review: SourceRetentionReview };
export type RetentionQueuePage = { items: RetentionQueueItem[]; next_cursor: string | null };
export type ArtifactCleanupCandidate = {
  ref: string;
  kind: "source_capture" | "source_extraction";
  workspace_id: string;
  source_id: string;
  capture_id?: string;
  extraction_id?: string;
  bytes: number;
  purged_at: string;
  created_at: string;
};
export type ArtifactCleanupInventory = {
  items: ArtifactCleanupCandidate[];
  candidate_count: number;
  candidate_bytes: number;
  recent_sweeps: ArtifactCleanupSweepRun[];
};
export type ArtifactCleanupReview = {
  review_id: string;
  workspace_id: string;
  created_by: string;
  updated_by: string;
  status: "none" | "open" | "completed" | "discarded";
  items: ArtifactCleanupCandidate[];
  selected_refs: string[];
  created_at: string;
  updated_at: string;
  completed_at?: string;
  sweep_id?: string;
  discarded_by?: string;
  discarded_at?: string;
  discard_reason?: string;
};
export type ArtifactCleanupReviewSummary = {
  review_id: string;
  workspace_id: string;
  created_by: string;
  updated_by: string;
  status: "open" | "completed" | "discarded";
  item_count: number;
  item_bytes: number;
  created_at: string;
  updated_at: string;
  completed_at?: string;
  sweep_id?: string;
  discarded_by?: string;
  discarded_at?: string;
  discard_reason?: string;
};
export type ArtifactCleanupReviewPage = { items: ArtifactCleanupReviewSummary[]; count: number };
export type ArtifactCleanupSweepRun = {
  sweep_id: string;
  workspace_id: string;
  requested_by: string;
  review_id?: string;
  status: "running" | "completed" | "failed" | "interrupted";
  limit: number;
  candidate_count: number;
  candidate_bytes: number;
  deleted_count: number;
  deleted_bytes: number;
  already_gone_count: number;
  skipped_count: number;
  error?: string;
  started_at: string;
  finished_at?: string;
};
export type ArtifactCleanupResult = {
  inventory: ArtifactCleanupInventory;
  run: ArtifactCleanupSweepRun;
  deleted: ArtifactCleanupCandidate[];
  already_gone: ArtifactCleanupCandidate[];
  skipped: ArtifactCleanupCandidate[];
  deleted_bytes: number;
};
export type ArtifactLifecycleState = "protected" | "eligible" | "missing" | "swept" | "already_gone" | "mismatched" | "corrupted" | "unavailable";
export type ArtifactLifecycleStatus = {
  ref: string;
  kind: "source_capture" | "source_extraction";
  workspace_id: string;
  source_id: string;
  capture_id?: string;
  extraction_id?: string;
  bytes: number;
  purged_at?: string;
  created_at: string;
  reference_count: number;
  live_source_count: number;
  live_extraction_count: number;
  run_referenced: boolean;
  report_referenced: boolean;
  state: ArtifactLifecycleState;
  reason: string;
  last_sweep_id?: string;
  last_sweep_outcome?: "deleted" | "already_gone" | "skipped" | "failed";
  last_sweep_at?: string;
};
export type ArtifactLifecyclePage = {
  items: ArtifactLifecycleStatus[];
  count: number;
  state_counts: Partial<Record<ArtifactLifecycleState, number>>;
  next_cursor: string | null;
};
export type ManualObservation = {
  observation_id: string;
  workspace_id: string;
  source_id: string;
  capture_id: string;
  extraction_id?: string;
  statement: string;
  quote: string;
  /** Unicode code-point offsets, never JavaScript UTF-16 indices. */
  quote_start: number;
  quote_end: number;
  locator?: string;
  author: string;
  recorded_at: string;
  origin: "manual";
};
export type AddObservation = {
  capture_id: string;
  extraction_id?: string;
  statement: string;
  quote: string;
  quote_start?: number;
  locator?: string;
};
export type CitationShare = {
  share_id: string;
  workspace_id: string;
  source_id: string;
  observation_id: string;
  created_by: string;
  created_at: string;
  revoked_at?: string;
  revoked_by?: string;
  token?: string;
};
export type CitationContext = {
  visibility: "recipient";
  redactions: string[];
  source_title: string;
  source_origin: string;
  source_url?: string;
  capture_version: number;
  captured_at: string;
  media_type: MediaType;
  derived: boolean;
  statement: string;
  quote: string;
  locator?: string;
};
